/* THIS FUNCTION JUST EXPORTS WORDS FOR STATE */
export default function langWords(){
    const _data = {
        'ua':{
            'importTemplate':'Імпортувати макет',
            'undo':'Відмінити дію',
            'redo':'Відтворити дію',
            'ellipse':'Кружечок',
            'newTemplate':'Новий макет',
            'exportTemplate':'Експортувати макет',
            'language':'Мова',
            'settings':'Налаштування',
            'Block: ':'Блок: ',
            'Parent: ':'Батько: ',
            'Children: ':'Діти: ',
            'Neigbors: ':'Сусіди',
            'Edit':'Редактор',
            'Copy':'Копії',
            'Print':'Друк',
            'Template':'Макет',
            'Margin':'Відступи',
            'newBlock':'Додати блок',
            'removeBlock':'Видалити блок',
            'Align':'Вирівнювння',
            'Text':'Текст',
            'Content':'Зміст',
            'Custom CSS':'Свій CSS',
            'Data to copy':'Данні для копіювання',
            'Select CSV':'Імпорувати CSV',
            'Add copy':'Додати копію',
            'No copy to show':'Немає копії для показу',
            'Create copy to print':'Додай копію щоб друкувати',
            //MI
            'name':'Назва',
            'A5':'А5',
            'A4':'А4',
            'A3':'А3',
            'pageSize':'Розмір сторінки',
            'Portrait':'Вертикально',
            'Landscape':'Горизонтально',
            'pageOrientation':'Оріентація сторінки',
            'marginTop':'Відступ зверху',
            'marginBottom':'Відступ знизу',
            'marginLeft':'Відступ зліва',
            'marginRight':'Відступ зправа',
            'width':'Ширина',
            'height':'Висота',
            'Inline':'Строка',
            'Flex':'Блок',
            'Inherit':'Наслідує',
            'displayType':'Режим відображення',
            'backgroundColor':'Фоновий колір',
            'Top':'Зверху',
            'Center':'Центр',
            'Bottom':'Знизу',
            'Space around':'Відступи навколо',
            'Space between':'Відступи поміж',
            'Space evenly':'Рівні відступи',
            'alignVertical':'Вирівнування',
            'Left':'Зліва',
            'Right':'Зправа',
            'variableTitle':'Назва змінної',
            'alignHorizontal':'Рівняння горизонтально',
            'Arial':'Arial',
            'Times New Roman':'Times New Roman',
            'Calibri':'Calibri',
            'Roboto':'Roboto',
            'fontFamily':'Шрифт',
            'fontSize':'Розмір тексту',
            'fontColor':'Колір тексту',
            'Thin':'Тонкий',
            'Normal':'Нормальний',
            'Bold':'Жирний',
            'Bolder':'Жирніший',
            'fontBold':'Товщина тексту',
            'Not italic':'Прямий',
            'Italic':'Нахилений',
            'fontItalic':'Нахиленість текст',
            'Fixed':'Статична',
            'Variable':'Змінна',
            'Selector':'Вибір',
            'Copy from':'Копіювати з',
            'valueType':'Тип даних',
            'innerText':'Текст',
            'Delete existing?':'Видалити існуючу?',
            'customStyle':'Свій CSS',
            'Block':'Блок',
            'Unselected':'Не обрано',
            'Copy':'Копія',
        }
    }
    return _data;
}